#ifndef TRITONSORT_SORT_CONSTANTS_H
#define TRITONSORT_SORT_CONSTANTS_H

enum SortAlgorithm {
  UNDEFINED,
  RADIX_SORT_AP,
  RADIX_SORT_MAPREDUCE,
  QUICK_SORT
};

#endif //TRITONSORT_SORT_CONSTANTS_H
