FIND_PATH(ZLIB_INCLUDE_DIR zlib.h)
FIND_LIBRARY(ZLIB_LIBRARY z)

MARK_AS_ADVANCED(ZLIB ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZLIB "zlib is required" ZLIB_INCLUDE_DIR ZLIB_LIBRARY)

INCLUDE_DIRECTORIES(${ZLIB_INCLUDE_DIR})