MACRO(RECURSE_CC_FILES
    DIR)
  GET_FILENAME_COMPONENT(MyDirName ${DIR} NAME)
  FILE(GLOB_RECURSE ${MyDirName}_Files "${DIR}/*.cc")

ENDMACRO(RECURSE_CC_FILES)

MACRO(RECURSE_CC_FILES_WITH_NAME
    LIBNAME DIR)
  GET_FILENAME_COMPONENT(MyDirName ${DIR} NAME)
  FILE(GLOB_RECURSE ${LIBNAME}_Files "${DIR}/*.cc")

ENDMACRO(RECURSE_CC_FILES_WITH_NAME)
