#ifndef THEMIS_MR_WEX_ADJACENCY_TO_PAGERANK_REDUCER_H
#define THEMIS_MR_WEX_ADJACENCY_TO_PAGERANK_REDUCER_H

#include "mapreduce/functions/reduce/ReduceFunction.h"

/**
   This reduce function converts a set of adjacencies between Wikipedia pages
   generated by WEXLinkExtractorMapFunction into an adjacency list suitable for
   input into PageRankMapFunction by concatenating the adjacent pages for a
   given page togetherinto a list and giving each page an initial PageRank of
   1. In the process, it also hashes the page names.
 */
class WEXAdjacencyToPageRankReducer : public ReduceFunction {
public:
  void reduce(
    const uint8_t* key, uint64_t keyLength, KVPairIterator& iterator,
    KVPairWriterInterface& writer);
private:
  static const double INITIAL_PAGERANK = 1.0;
};

#endif // THEMIS_MR_WEX_ADJACENCY_TO_PAGERANK_REDUCER_H
